name: Docker Build and Extract Artifacts

on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: 配置docker insecure registry
        run: | 
          # 创建 Docker 配置目录
          mkdir -p /etc/docker
          # 配置不安全的私有注册表
          echo '{"insecure-registries":["${{ secrets.MY_HOST }}:5000"]}' | sudo tee /etc/docker/daemon.json
          # 重启 Docker 服务
          sudo systemctl restart docker
      - name: Verify Docker configuration
        run: |
          # 检查 Docker 信息
          docker info
          # 查看 daemon.json 配置
          cat /etc/docker/daemon.json
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 配置buildx
        uses: docker/setup-buildx-action@v2
        with: 
          install: true
      - name: 构建Docker镜像
        run:  |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t my-web-app .
      - name: 登陆到私人仓库
        run: |
          docker login ${{ secrets.MY_HOST }}:5000 -u ${{ secrets.MY_USER }} -p ${{ secrets.MY_PWD }}
      - name: 给镜像打标签
        run: |
          docker tag my-web-app ${{ secrets.MY_HOST }}:5000/my-web-app:latest
      - name: 上传到私人仓库
        run: |
          docker push ${{ secrets.MY_HOST }}:5000/my-web-app:latest
      - name: 查看
        run: |
          tree .
      

     
        
