name: Docker Build and Extract Artifacts

on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 配置buildx
        uses: docker/setup-buildx-action@v2
        with: 
          install: true
      - name: 构建Docker镜像
        run:  |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t my-web-app .
      - name: 登陆到私人仓库
        run: |
          docker login ${{ prd.MY_HOST }}:5000 -u ${{ prd.MY_USER }} -p ${{ prd.MY_PWD }}
      - name: 给镜像打标签
        run: |
          docker tag my-web-app ${{ prd.MY_HOST }}:5000/my-web-app:latest
      - name: 上传到私人仓库
        run: |
          docker push ${{ prd.MY_HOST }}:5000/my-web-app:latest
      - name: 查看
        run: |
          tree .
      

     
        
