name: Docker Build and Extract Artifacts

on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 配置 buildx 并启用 insecure registry
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
            env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
            env.BUILDKIT_STEP_LOG_MAX_SPEED=1048576
      - name: 配置 insecure registry
        run: |
          echo '{"insecure-registries":["47.115.133.215:5000"]}' | sudo tee /etc/docker/daemon.json
          # 验证配置文件内容
          cat /etc/docker/daemon.json
          sudo systemctl restart docker
          docker info | grep -A2 'Insecure Registries'  # 验证配置
      - name: 验证 Buildx 配置
        run: |
          docker buildx inspect
          docker buildx version
      - name: 登陆到私人仓库
        run: |
          docker login 47.115.133.215:5000 -u ${{ secrets.MY_USER }} -p ${{ secrets.MY_PWD }}
      - name: Verify Docker configuration
        run: |
          # 检查 Docker 信息
          docker info
          # 查看 daemon.json 配置
          cat /etc/docker/daemon.json
      - name: 构建Docker镜像
        run:  |
          docker buildx build \
            --platform linux/amd64 \
            --tag 47.115.133.215:5000/my-web-app:latest \
            --push \
            .
      - name: 查看
        run: |
          tree .
      

     
        
