name: Docker Build and Extract Artifacts

on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: login
        run: |
          # 安装 sshpass（用于非交互密码登录）
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.MY_SSH_PAS }}" ssh -o StrictHostKeyChecking=no \
          -p ${{ secrets.MY_SSH_PORT }} ${{ secrets.SSH_HOST }} << 'EOF'

          rm -rf /usr/lmt/apps
          cd /usr/lmt
          mkdir apps
          cd apps
          git pull origin main

          docker build -t my-web-app:latest .

          docker compose down && docker compose up -d

          EOF
      

     
        
