name: Docker Build and Extract Artifacts

on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 配置buildx
        uses: docker/setup-buildx-action@v2
        with: 
          install: true
      - name: 构建Docker镜像
        run:  |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t my-web-app .
      - name: 构建临时容器
        id: create_container
        run: |
          CONTAINER_ID=$(docker create my-web-app)
          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
      - name: 提取打包产物
        run: |
          mkdir -p ./extracted-artifacts
          docker cp $CONTAINER_ID:/app/dist/. ./extracted-artifacts/
      - name: 移动产物到指定目录
        run: |
          mkdir -p ./target-directory
          mv ./extracted-artifacts/* ./target-directory/
      - name: 查看
        run: |
          tree .
      

     
        
