name: Docker Build and Extract Artifacts

on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: login
        run: |
          # 安装 sshpass（用于非交互密码登录）
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.MY_SSH_PAS }}" ssh -o StrictHostKeyChecking=no \
          -p ${{ secrets.MY_SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

          rm -rf /usr/lmt/apps
          cd /usr/lmt
          mkdir apps
          cd apps
          
          # 检查是否为 Git 仓库
          if [ ! -d .git ]; then
            # 首次部署：克隆仓库
            git clone https://github.com/your-username/your-repo.git .
          else
            # 已有仓库：拉取更新
            git pull origin main
          fi
          docker build -t my-web-app:latest .

          docker compose down && docker compose up -d

          EOF
      

     
        
